//
// Created by desktop on 10/30/24.
//
#include "use_effects.h"
#include "array"

namespace Use_Effects {

     std::array<std::function<void(Unit::Unit &unit)>, 255> Item_Effect_Map;

     void Trigger_Effect(Unit::Unit &unit, ItemEffectUID effectUid) {
	     Item_Effect_Map[effectUid](unit);
     }


     void NOTHING(Unit::Unit &unit) {
	     std::cout << "The potion does Nothing." << std::endl;
     }

     void Heal(Unit::Unit &unit) {
	     std::cout << "unit: " << unit.stats.health << std::endl;
	     unit.stats.health += Utils::Random(20, 40);
	     std::cout << "unit: " << unit.stats.health << std::endl;
     }


     //TODO: add item effects
     void Init() {
	     Item_Effect_Map[0] = NOTHING;
	     Item_Effect_Map[1] = Heal;
	     Item_Effect_Map[2] = NOTHING;
	     Item_Effect_Map[3] = NOTHING;
	     Item_Effect_Map[4] = NOTHING;
	     Item_Effect_Map[5] = NOTHING;
	     Item_Effect_Map[6] = NOTHING;
	     Item_Effect_Map[7] = NOTHING;
	     Item_Effect_Map[8] = NOTHING;
	     Item_Effect_Map[9] = NOTHING;
	     Item_Effect_Map[10] = NOTHING;
	     Item_Effect_Map[11] = NOTHING;
	     Item_Effect_Map[12] = NOTHING;
	     Item_Effect_Map[13] = NOTHING;
	     Item_Effect_Map[14] = NOTHING;
	     Item_Effect_Map[15] = NOTHING;
	     Item_Effect_Map[16] = NOTHING;
	     Item_Effect_Map[17] = NOTHING;
	     Item_Effect_Map[18] = NOTHING;
	     Item_Effect_Map[19] = NOTHING;
	     Item_Effect_Map[20] = NOTHING;
	     Item_Effect_Map[21] = NOTHING;
	     Item_Effect_Map[22] = NOTHING;
	     Item_Effect_Map[23] = NOTHING;
	     Item_Effect_Map[24] = NOTHING;
	     Item_Effect_Map[25] = NOTHING;
	     Item_Effect_Map[26] = NOTHING;
	     Item_Effect_Map[27] = NOTHING;
	     Item_Effect_Map[28] = NOTHING;
	     Item_Effect_Map[29] = NOTHING;
	     Item_Effect_Map[30] = NOTHING;
	     Item_Effect_Map[31] = NOTHING;
	     Item_Effect_Map[32] = NOTHING;
	     Item_Effect_Map[33] = NOTHING;
	     Item_Effect_Map[34] = NOTHING;
	     Item_Effect_Map[35] = NOTHING;
	     Item_Effect_Map[36] = NOTHING;
	     Item_Effect_Map[37] = NOTHING;
	     Item_Effect_Map[38] = NOTHING;
	     Item_Effect_Map[39] = NOTHING;
	     Item_Effect_Map[40] = NOTHING;
	     Item_Effect_Map[41] = NOTHING;
	     Item_Effect_Map[42] = NOTHING;
	     Item_Effect_Map[43] = NOTHING;
	     Item_Effect_Map[44] = NOTHING;
	     Item_Effect_Map[45] = NOTHING;
	     Item_Effect_Map[46] = NOTHING;
	     Item_Effect_Map[47] = NOTHING;
	     Item_Effect_Map[48] = NOTHING;
	     Item_Effect_Map[49] = NOTHING;
	     Item_Effect_Map[50] = NOTHING;
	     Item_Effect_Map[51] = NOTHING;
	     Item_Effect_Map[52] = NOTHING;
	     Item_Effect_Map[53] = NOTHING;
	     Item_Effect_Map[54] = NOTHING;
	     Item_Effect_Map[55] = NOTHING;
	     Item_Effect_Map[56] = NOTHING;
	     Item_Effect_Map[57] = NOTHING;
	     Item_Effect_Map[58] = NOTHING;
	     Item_Effect_Map[59] = NOTHING;
	     Item_Effect_Map[60] = NOTHING;
	     Item_Effect_Map[61] = NOTHING;
	     Item_Effect_Map[62] = NOTHING;
	     Item_Effect_Map[63] = NOTHING;
	     Item_Effect_Map[64] = NOTHING;
	     Item_Effect_Map[65] = NOTHING;
	     Item_Effect_Map[66] = NOTHING;
	     Item_Effect_Map[67] = NOTHING;
	     Item_Effect_Map[68] = NOTHING;
	     Item_Effect_Map[69] = NOTHING;
	     Item_Effect_Map[70] = NOTHING;
	     Item_Effect_Map[71] = NOTHING;
	     Item_Effect_Map[72] = NOTHING;
	     Item_Effect_Map[73] = NOTHING;
	     Item_Effect_Map[74] = NOTHING;
	     Item_Effect_Map[75] = NOTHING;
	     Item_Effect_Map[76] = NOTHING;
	     Item_Effect_Map[77] = NOTHING;
	     Item_Effect_Map[78] = NOTHING;
	     Item_Effect_Map[79] = NOTHING;
	     Item_Effect_Map[80] = NOTHING;
	     Item_Effect_Map[81] = NOTHING;
	     Item_Effect_Map[82] = NOTHING;
	     Item_Effect_Map[83] = NOTHING;
	     Item_Effect_Map[84] = NOTHING;
	     Item_Effect_Map[85] = NOTHING;
	     Item_Effect_Map[86] = NOTHING;
	     Item_Effect_Map[87] = NOTHING;
	     Item_Effect_Map[88] = NOTHING;
	     Item_Effect_Map[89] = NOTHING;
	     Item_Effect_Map[90] = NOTHING;
	     Item_Effect_Map[91] = NOTHING;
	     Item_Effect_Map[92] = NOTHING;
	     Item_Effect_Map[93] = NOTHING;
	     Item_Effect_Map[94] = NOTHING;
	     Item_Effect_Map[95] = NOTHING;
	     Item_Effect_Map[96] = NOTHING;
	     Item_Effect_Map[97] = NOTHING;
	     Item_Effect_Map[98] = NOTHING;
	     Item_Effect_Map[99] = NOTHING;
	     Item_Effect_Map[100] = NOTHING;
	     Item_Effect_Map[101] = NOTHING;
	     Item_Effect_Map[102] = NOTHING;
	     Item_Effect_Map[103] = NOTHING;
	     Item_Effect_Map[104] = NOTHING;
	     Item_Effect_Map[105] = NOTHING;
	     Item_Effect_Map[106] = NOTHING;
	     Item_Effect_Map[107] = NOTHING;
	     Item_Effect_Map[108] = NOTHING;
	     Item_Effect_Map[109] = NOTHING;
	     Item_Effect_Map[110] = NOTHING;
	     Item_Effect_Map[111] = NOTHING;
	     Item_Effect_Map[112] = NOTHING;
	     Item_Effect_Map[113] = NOTHING;
	     Item_Effect_Map[114] = NOTHING;
	     Item_Effect_Map[115] = NOTHING;
	     Item_Effect_Map[116] = NOTHING;
	     Item_Effect_Map[117] = NOTHING;
	     Item_Effect_Map[118] = NOTHING;
	     Item_Effect_Map[119] = NOTHING;
	     Item_Effect_Map[120] = NOTHING;
	     Item_Effect_Map[121] = NOTHING;
	     Item_Effect_Map[122] = NOTHING;
	     Item_Effect_Map[123] = NOTHING;
	     Item_Effect_Map[124] = NOTHING;
	     Item_Effect_Map[125] = NOTHING;
	     Item_Effect_Map[126] = NOTHING;
	     Item_Effect_Map[127] = NOTHING;
	     Item_Effect_Map[128] = NOTHING;
	     Item_Effect_Map[129] = NOTHING;
	     Item_Effect_Map[130] = NOTHING;
	     Item_Effect_Map[131] = NOTHING;
	     Item_Effect_Map[132] = NOTHING;
	     Item_Effect_Map[133] = NOTHING;
	     Item_Effect_Map[134] = NOTHING;
	     Item_Effect_Map[135] = NOTHING;
	     Item_Effect_Map[136] = NOTHING;
	     Item_Effect_Map[137] = NOTHING;
	     Item_Effect_Map[138] = NOTHING;
	     Item_Effect_Map[139] = NOTHING;
	     Item_Effect_Map[140] = NOTHING;
	     Item_Effect_Map[141] = NOTHING;
	     Item_Effect_Map[142] = NOTHING;
	     Item_Effect_Map[143] = NOTHING;
	     Item_Effect_Map[144] = NOTHING;
	     Item_Effect_Map[145] = NOTHING;
	     Item_Effect_Map[146] = NOTHING;
	     Item_Effect_Map[147] = NOTHING;
	     Item_Effect_Map[148] = NOTHING;
	     Item_Effect_Map[149] = NOTHING;
	     Item_Effect_Map[150] = NOTHING;
	     Item_Effect_Map[151] = NOTHING;
	     Item_Effect_Map[152] = NOTHING;
	     Item_Effect_Map[153] = NOTHING;
	     Item_Effect_Map[154] = NOTHING;
	     Item_Effect_Map[155] = NOTHING;
	     Item_Effect_Map[156] = NOTHING;
	     Item_Effect_Map[157] = NOTHING;
	     Item_Effect_Map[158] = NOTHING;
	     Item_Effect_Map[159] = NOTHING;
	     Item_Effect_Map[160] = NOTHING;
	     Item_Effect_Map[161] = NOTHING;
	     Item_Effect_Map[162] = NOTHING;
	     Item_Effect_Map[163] = NOTHING;
	     Item_Effect_Map[164] = NOTHING;
	     Item_Effect_Map[165] = NOTHING;
	     Item_Effect_Map[166] = NOTHING;
	     Item_Effect_Map[167] = NOTHING;
	     Item_Effect_Map[168] = NOTHING;
	     Item_Effect_Map[169] = NOTHING;
	     Item_Effect_Map[170] = NOTHING;
	     Item_Effect_Map[171] = NOTHING;
	     Item_Effect_Map[172] = NOTHING;
	     Item_Effect_Map[173] = NOTHING;
	     Item_Effect_Map[174] = NOTHING;
	     Item_Effect_Map[175] = NOTHING;
	     Item_Effect_Map[176] = NOTHING;
	     Item_Effect_Map[177] = NOTHING;
	     Item_Effect_Map[178] = NOTHING;
	     Item_Effect_Map[179] = NOTHING;
	     Item_Effect_Map[180] = NOTHING;
	     Item_Effect_Map[181] = NOTHING;
	     Item_Effect_Map[182] = NOTHING;
	     Item_Effect_Map[183] = NOTHING;
	     Item_Effect_Map[184] = NOTHING;
	     Item_Effect_Map[185] = NOTHING;
	     Item_Effect_Map[186] = NOTHING;
	     Item_Effect_Map[187] = NOTHING;
	     Item_Effect_Map[188] = NOTHING;
	     Item_Effect_Map[189] = NOTHING;
	     Item_Effect_Map[190] = NOTHING;
	     Item_Effect_Map[191] = NOTHING;
	     Item_Effect_Map[192] = NOTHING;
	     Item_Effect_Map[193] = NOTHING;
	     Item_Effect_Map[194] = NOTHING;
	     Item_Effect_Map[195] = NOTHING;
	     Item_Effect_Map[196] = NOTHING;
	     Item_Effect_Map[197] = NOTHING;
	     Item_Effect_Map[198] = NOTHING;
	     Item_Effect_Map[199] = NOTHING;
	     Item_Effect_Map[200] = NOTHING;
	     Item_Effect_Map[201] = NOTHING;
	     Item_Effect_Map[202] = NOTHING;
	     Item_Effect_Map[203] = NOTHING;
	     Item_Effect_Map[204] = NOTHING;
	     Item_Effect_Map[205] = NOTHING;
	     Item_Effect_Map[206] = NOTHING;
	     Item_Effect_Map[207] = NOTHING;
	     Item_Effect_Map[208] = NOTHING;
	     Item_Effect_Map[209] = NOTHING;
	     Item_Effect_Map[210] = NOTHING;
	     Item_Effect_Map[211] = NOTHING;
	     Item_Effect_Map[212] = NOTHING;
	     Item_Effect_Map[213] = NOTHING;
	     Item_Effect_Map[214] = NOTHING;
	     Item_Effect_Map[215] = NOTHING;
	     Item_Effect_Map[216] = NOTHING;
	     Item_Effect_Map[217] = NOTHING;
	     Item_Effect_Map[218] = NOTHING;
	     Item_Effect_Map[219] = NOTHING;
	     Item_Effect_Map[220] = NOTHING;
	     Item_Effect_Map[221] = NOTHING;
	     Item_Effect_Map[222] = NOTHING;
	     Item_Effect_Map[223] = NOTHING;
	     Item_Effect_Map[224] = NOTHING;
	     Item_Effect_Map[225] = NOTHING;
	     Item_Effect_Map[226] = NOTHING;
	     Item_Effect_Map[227] = NOTHING;
	     Item_Effect_Map[228] = NOTHING;
	     Item_Effect_Map[229] = NOTHING;
	     Item_Effect_Map[230] = NOTHING;
	     Item_Effect_Map[231] = NOTHING;
	     Item_Effect_Map[232] = NOTHING;
	     Item_Effect_Map[233] = NOTHING;
	     Item_Effect_Map[234] = NOTHING;
	     Item_Effect_Map[235] = NOTHING;
	     Item_Effect_Map[236] = NOTHING;
	     Item_Effect_Map[237] = NOTHING;
	     Item_Effect_Map[238] = NOTHING;
	     Item_Effect_Map[239] = NOTHING;
	     Item_Effect_Map[240] = NOTHING;
	     Item_Effect_Map[241] = NOTHING;
	     Item_Effect_Map[242] = NOTHING;
	     Item_Effect_Map[243] = NOTHING;
	     Item_Effect_Map[244] = NOTHING;
	     Item_Effect_Map[245] = NOTHING;
	     Item_Effect_Map[246] = NOTHING;
	     Item_Effect_Map[247] = NOTHING;
	     Item_Effect_Map[248] = NOTHING;
	     Item_Effect_Map[249] = NOTHING;
	     Item_Effect_Map[250] = NOTHING;
	     Item_Effect_Map[251] = NOTHING;
	     Item_Effect_Map[252] = NOTHING;
	     Item_Effect_Map[253] = NOTHING;
	     Item_Effect_Map[254] = NOTHING;
     }
}
